apiVersion: v1
kind: ConfigMap
metadata: 
  name: api-config
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  PG_HOST: "pg-service"
  PG_PORT: "5432"
  PG_POOL_MIN: "1"
  PG_POOL_MAX: "10"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_MAX_CONNECTIONS: "10"