apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    name: "{{ .Release.Name }}-api"
spec:
  selector:
    matchLabels:
      app: api
  replicas: {{ .Values.api.replicaCount }}
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          ports:
            containerPort: 8000
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secret


