apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: "{{ .Release.Name }}-api"
spec:
  selector:
    matchLabels:
      app: api
  replicas: 2
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: xazmo/inci_plat:api-v1.0
          ports:
            containerPort: 8000


