apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    name: "{{ .Release.Name }}-front"
spec:
  selector:
    matchLabels:
      app: front
  replicas: {{ .Values.frontend.replicaCount }}
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: 8080
