apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-front"
spec:
  selector:
    matchLabels:
      app: front
  replicas: 2
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: xazmo/inci_plat:front-v1.0
          ports:
            - containerPort: 8080
