apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-ingress
  namespace: incident-dev
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "10"
spec:
  ingressClassName: nginx
  rules:
  - host: dev.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: { name: front-clusterip, port: { number: 8080 } }
      
      - path: /api
        pathType: Prefix
        backend:
          service: { name: api-service, port: { number: 8000 } }