apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api
  namespace: {{ .Values.namespace }}
  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: api-service
  endpoints:
    - port: http
      path: /metrics
      intervals: 30s