apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    name: "{{ .Release.Name }}-worker"
spec:
  revisionHistoryLimit: {{ .Values.frontend.revisionHistoryLimit }}
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          envFrom:
            - secretRef:
              name: api-secret
            - configMapRef:
              name: api-config