apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    name: "{{ .Release.Name }}-worker"
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 2
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag | default .Chart.AppVersion }}"