
#API Values
api:
  image:
    repository: xazmo/incident-api
    pullPolicy: IfNotPresent
    tag: "sha-191d650"
  replicaCount: 2
  revisionHistoryLimit: 3
#Frontend Values
frontend:
  image:
    repository: xazmo/incident-front
    pullPolicy: IfNotPresent
    tag: "sha-3932046"
  replicaCount: 2
  revisionHistoryLimit: 3
#Worker Values
worker:
  image:
    repository: xazmo/incident-worker
    pullPolicy: IfNotPresent
    tag: "sha-82428f9"
  replicaCount: 1
  revisionHistoryLimit: 3
#Redis Values
redis:
  replicaCount: 1
#Postgres Values
postgres:
  replicaCount: 1
