replicaCount: 1
api:
  image:
    repository: xazmo/incident-api
    pullPolicy: IfNotPresent
    tag: "sha-2ad6d66"
frontend:
  image:
    repository: xazmo/incident-front
    pullPolicy: IfNotPresent
    tag: "sha-0563b9f"
worker:
  image:
    repository: xazmo/incident-worker
    pullPolicy: IfNotPresent
    tag: "sha-451af1d"
