
#API Values
api:
  image:
    repository: xazmo/incident-api
    pullPolicy: IfNotPresent
    tag: "sha-2ad6d66"
  replicaCount: 2
#Frontend Values
frontend:
  image:
    repository: xazmo/incident-front
    pullPolicy: IfNotPresent
    tag: "sha-22e9c30"
  replicaCount: 2
#Worker Values
worker:
  image:
    repository: xazmo/incident-worker
    pullPolicy: IfNotPresent
    tag: "sha-4193013"
  replicaCount: 1
#Redis Values
redis:
  replicaCount: 1
#Postgres Values
postgres:
  replicaCount: 1
